In [ ]:
#Lab Session 11
#Name: Anant Dubey
#PRN: 1132220920

In [2]:
#Q1

import numpy as np
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [3]:
#Array in NumPy

a = np.array([1, 2, 3, 4, 5, 6])
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [4]:
#Sorting array elements

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#Concatenation 

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
#Printing the shape of an array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [7]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [8]:
#Converting 1-D to 2-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
#Converting from 1-D to 3-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
#Iterating Arrays

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [11]:
#iterating through each scalar element of 2-D array

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [12]:
#joining two arrays

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [13]:
#joining two 2-D arrays along rows


arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
#Joining array using stack function

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
#Splitting numpy arrays

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [16]:
#Splitting 2-D Arrays

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [17]:
#Splitting 2-D into three 2-D arrays

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [18]:
#Searching arrays
#Finding indexes where value is 4 

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [19]:
#Finding indexes where value is even

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [20]:
#Q2

#Mathematical Functions
import numpy as np

#initialize a list
listA = [4, 16, 9, 1, 25, 49]

#Square Root

#find square root of items in the list
output = np.sqrt(listA)
print(output)

[2. 4. 3. 1. 5. 7.]


In [21]:
#Square root of complex numbers

#initialize a list
listA = [4+1j, 9+16j]

#find square root of items in the list
output = np.sqrt(listA)

print(output)

[2.01532946+0.24809839j 3.69848346+2.16304875j]


In [22]:
#Square root of negative answers

#initialize a list
listA = [-4, 9]

#find square root of items in the list
output = np.sqrt(listA)

print(output)

[nan  3.]


C:\Users\anant\AppData\Local\Temp\ipykernel_14044\3062388682.py:7: RuntimeWarning: invalid value encountered in sqrt
  output = np.sqrt(listA)


In [23]:
#Mean

#Mean of numpy array 

A = np.array([[2, 1], [5, 4]])

#compute mean
output = np.mean(A)

print(output)

3.0


In [24]:
#Mean of numpy array along an axis

A = np.array([[2, 1], [5, 4]])

#compute mean
output = np.mean(A, axis=0)

print(output)

[3.5 2.5]


In [25]:
#Mean of numpy array along multiple axis

#initialize array
A = np.array([[[2, 1], [5, 4]], [[3, 9], [6, 8]]])

#compute mean
output = np.mean(A, axis=(0, 1))

print(output)

[4.  5.5]


In [26]:
#NumPy Maximum Value

#Max value of numpy array 

arr = np.random.randint(10, size=(4,5))
print('array\n', arr)
#find maximum value
max_value = np.max(arr)
print('Maximum value in array\n',max_value)

array
 [[1 4 4 1 9]
 [6 8 4 5 6]
 [5 3 0 8 0]
 [5 2 4 7 6]]
Maximum value in array
 9


In [27]:
# Maximum value of numpy array with float values

arr = np.random.rand(6).reshape(2,3)
print('array\n', arr)
#find maximum value
max_value = np.max(arr)
print('Maximum value in array\n',max_value)

array
 [[0.40481    0.78718898 0.01428442]
 [0.13046558 0.56463086 0.3741523 ]]
Maximum value in array
 0.7871889836915421


In [28]:
#NumPy Standard Deviation

#SD of 1-D Array 

A = np.array([2, 1, 6])

#compute standard deviation
output = np.std(A)

print(output)

2.160246899469287


In [29]:
#SD of 2-D Array 

#initialize array
A = np.array([[2, 3], [6, 5]])

#compute standard deviation
output = np.std(A)

print(output)

1.5811388300841898


In [30]:
#Standard Deviation of array along an axis

#initialize array
A = np.array([[2, 3], [6, 5]])

#compute standard deviation
output = np.std(A, axis=0)

print(output)

[2. 1.]


In [31]:
#NumPy Convert Array to a Python List

import numpy

arr = numpy.array([[1, 2], [3, 4]])
x = arr.tolist()

print("Numpy Array :\n", arr)
print("\nList :\n", x)

Numpy Array :
 [[1 2]
 [3 4]]

List :
 [[1, 2], [3, 4]]


In [32]:
#NumPy logical Functions

#Check if all elements in array are True

arr = np.array([[True,True],[True,True]])
result = np.all(arr)
print(result)

True


In [33]:
#Check if all elements in array are True along an axis

arr = np.array([[True,True], [True,False], [True,False]])
result = np.all(arr, axis=1)
print(result)

[ True False False]


In [34]:
#NumPy Sum 

a = np.array([4, 5, 3, 7])
print('input\n',a)

b = np.sum(a)
print('sum\n',b)

input
 [4 5 3 7]
sum
 19


In [35]:
#Convert List to NumPy Array 

x = list([1, 2, 4, 8, 16, 32])
arr = numpy.array(x)

print("List :", x)
print("Numpy Array :", arr)

List : [1, 2, 4, 8, 16, 32]
Numpy Array : [ 1  2  4  8 16 32]
